
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'b\x0e\xc7H\xb8M"\x17\xb9j\xc2\\r\xf8\xbeF'
    
_lr_action_items = {'INTDIVISION':([1,2,9,10,11,12,13,14,],[-7,4,4,4,4,4,4,4,]),'TIMES':([1,2,9,10,11,12,13,14,],[-7,5,5,5,5,5,5,5,]),'PLUS':([1,2,9,10,11,12,13,14,],[-7,6,6,6,6,6,6,6,]),'INTEGER':([0,3,4,5,6,7,8,],[1,1,1,1,1,1,1,]),'$end':([1,2,9,10,11,12,13,14,],[-7,0,-6,-3,-5,-1,-2,-4,]),'MINUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,],[3,-7,7,3,3,3,3,3,3,7,7,7,7,7,7,]),'RESTDIVISION':([1,2,9,10,11,12,13,14,],[-7,8,8,8,8,8,8,8,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,4,5,6,7,8,],[2,9,10,11,12,13,14,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binary','C:\\Users\\manuggz\\Setlan\\Setlan\\Entrega2(Parser)\\parser.py',14),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binary','C:\\Users\\manuggz\\Setlan\\Setlan\\Entrega2(Parser)\\parser.py',15),
  ('expression -> expression INTDIVISION expression','expression',3,'p_expression_binary','C:\\Users\\manuggz\\Setlan\\Setlan\\Entrega2(Parser)\\parser.py',16),
  ('expression -> expression RESTDIVISION expression','expression',3,'p_expression_binary','C:\\Users\\manuggz\\Setlan\\Setlan\\Entrega2(Parser)\\parser.py',17),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binary','C:\\Users\\manuggz\\Setlan\\Setlan\\Entrega2(Parser)\\parser.py',18),
  ('expression -> MINUS expression','expression',2,'p_expression_unary','C:\\Users\\manuggz\\Setlan\\Setlan\\Entrega2(Parser)\\parser.py',22),
  ('expression -> INTEGER','expression',1,'p_integer','C:\\Users\\manuggz\\Setlan\\Setlan\\Entrega2(Parser)\\parser.py',26),
]
